// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Game: typeof import('./components/Game.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    MineBlock: typeof import('./components/MineBlock.vue')['default']
    MineSweeper: typeof import('./components/MineSweeper.vue')['default']
    WebcamNN: typeof import('./components/WebcamNN.vue')['default']
  }
}

export { }
